config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  get 'static_pages/help'
  get 'password_resets/new'
  get 'password_resets/edit'

  root 'static_pages#home'

  namespace :admin do
    resources :products
    resources :users
    get :dashboard, to: 'dashboard#index'
  end

  get    :login,   to: 'sessions#new'
  post   :login,   to: 'sessions#create'
  delete :logout,  to: 'sessions#destroy'
  get :signup,  to: 'admin/users#new'

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:create, :edit, :update]
end

app/views/layouts/admin/_content_header.html.erb
<div id="content-header">
  <div id="breadcrumb"> <a href="index.html" title="Go to Home" class="tip-bottom"><i class="icon-home"></i> Home</a></div>
</div>

app/views/layouts/admin/_header.html.erb
<!--Header-part-->
<div id="header">
  <h1><a href="dashboard.html">ADDStock Admin</a></h1>
</div>
<!--close-Header-part-->

app/views/layouts/admin/_messages.html.erb
<!--top-Header-messaages-->
<div class="btn-group rightzero"> <a class="top_message tip-left" title="Manage Files"><i class="icon-file"></i></a> <a class="top_message tip-bottom" title="Manage Users"><i class="icon-user"></i></a> <a class="top_message tip-bottom" title="Manage Comments"><i class="icon-comment"></i><span class="label label-important">5</span></a> <a class="top_message tip-bottom" title="Manage Orders"><i class="icon-shopping-cart"></i></a> </div>
<!--close-top-Header-messaages-->

app/views/layouts/admin/_quick_action.html.erb
<div class="quick-actions_homepage">
    <ul class="quick-actions">
      <li> <a href="#"> <i class="icon-dashboard"></i> My Dashboard </a> </li>
      <li> <a href="#"> <i class="icon-shopping-bag"></i> Shopping Cart</a> </li>
      <li> <a href="#"> <i class="icon-web"></i> Web Marketing </a> </li>
      <li> <a href="#"> <i class="icon-people"></i> Manage Users </a> </li>
      <li> <a href="#"> <i class="icon-calendar"></i> Manage Events </a> </li>
    </ul>
</div>

app/views/layouts/admin/_sidebar.html.erb
<% active = :dashboard if active == nil %>

<div id="sidebar"><a href="#" class="visible-phone"><i class="icon icon-home"></i> Dashboard Icon</a>
  <ul>
    <li class="<%= 'active' if current_class?(:dashboard) %>"><%= link_to admin_dashboard_path do %><i class="icon icon-home"></i> <span>Dashboard</span><% end %> </li>
    <li> <a href="charts.html"><i class="icon icon-signal"></i> <span>Charts &amp; graphs</span></a> </li>
    <li> <a href="widgets.html"><i class="icon icon-inbox"></i> <span>Widgets</span></a> </li>
    <li><a href="tables.html"><i class="icon icon-th"></i> <span>Tables</span></a></li>
    <li><a href="grid.html"><i class="icon icon-fullscreen"></i> <span>Full width</span></a></li>
    <li class="submenu"> <a href="#"><i class="icon icon-th-list"></i> <span>Forms</span> <span class="label label-important">3</span></a>
      <ul>
        <li><a href="form-common.html">Basic Form</a></li>
        <li><a href="form-validation.html">Form with Validation</a></li>
        <li><a href="form-wizard.html">Form with Wizard</a></li>
      </ul>
    </li>
    <li><a href="buttons.html"><i class="icon icon-tint"></i> <span>Buttons &amp; icons</span></a></li>
    <li><a href="interface.html"><i class="icon icon-pencil"></i> <span>Eelements</span></a></li>
    <li class="submenu"> <a href="#"><i class="icon icon-file"></i> <span>Addons</span> <span class="label label-important">4</span></a>
      <ul>
        <li><a href="index2.html">Dashboard2</a></li>
        <li><a href="gallery.html">Gallery</a></li>
        <li><a href="calendar.html">Calendar</a></li>
        <li><a href="chat.html">Chat option</a></li>
      </ul>
    </li>
  </ul>
</div>

app/views/layouts/admin/_top_menu.html.erb
<!--top-Header-menu-->
<div id="user-nav" class="navbar navbar-inverse">
  <ul class="nav">
    <li class="" ><%= link_to admin_user_path(current_user) do %><i class="icon icon-user"></i> <span class="text">Profile</span><% end %></li>
    <li class=" dropdown" id="menu-messages"><a href="#" data-toggle="dropdown" data-target="#menu-messages" class="dropdown-toggle"><i class="icon icon-envelope"></i> <span class="text">Messages</span> <span class="label label-important">5</span> <b class="caret"></b></a>
      <ul class="dropdown-menu">
        <li><a class="sAdd" title="" href="#">new message</a></li>
        <li><a class="sInbox" title="" href="#">inbox</a></li>
        <li><a class="sOutbox" title="" href="#">outbox</a></li>
        <li><a class="sTrash" title="" href="#">trash</a></li>
      </ul>
    </li>
    <li class=""><a title="" href="#"><i class="icon icon-cog"></i> <span class="text">Settings</span></a></li>
    <li class=""><%= link_to logout_path, method: :delete do %><i class="icon icon-share-alt"></i> <span class="text">Logout</span><% end %></li>
  </ul>
</div>
<div id="search">
  <input type="text" placeholder="Search here..."/>
  <button type="submit" class="tip-left" title="Search"><i class="icon-search icon-white"></i></button>
</div>
<!--close-top-Header-menu-->