config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  get 'static_pages/help'
  get 'password_resets/new'
  get 'password_resets/edit'

  root 'static_pages#home'

  namespace :admin do
    resources :products
    resources :users
    get :dashboard, to: 'dashboard#index'
  end

  get    :login,   to: 'sessions#new'
  post   :login,   to: 'sessions#create'
  delete :logout,  to: 'sessions#destroy'
  get :signup,  to: 'admin/users#new'

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:create, :edit, :update]
end

app/models/admin/product.rb
class Admin::Product < ApplicationRecord
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :set_admin_product, only: [:show, :edit, :update, :destroy]

  # GET /admin/products
  # GET /admin/products.json
  def index
    @admin_products = Admin::Product.all
  end

  # GET /admin/products/1
  # GET /admin/products/1.json
  def show
  end

  # GET /admin/products/new
  def new
    @admin_product = Admin::Product.new
  end

  # GET /admin/products/1/edit
  def edit
  end

  # POST /admin/products
  # POST /admin/products.json
  def create
    @admin_product = Admin::Product.new(admin_product_params)

    respond_to do |format|
      if @admin_product.save
        format.html { redirect_to @admin_product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @admin_product }
      else
        format.html { render :new }
        format.json { render json: @admin_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/products/1
  # PATCH/PUT /admin/products/1.json
  def update
    respond_to do |format|
      if @admin_product.update(admin_product_params)
        format.html { redirect_to @admin_product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_product }
      else
        format.html { render :edit }
        format.json { render json: @admin_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/products/1
  # DELETE /admin/products/1.json
  def destroy
    @admin_product.destroy
    respond_to do |format|
      format.html { redirect_to admin_products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_product
      @admin_product = Admin::Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_product_params
      params.require(:admin_product).permit(:description, :barcode)
    end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= form_with(model: admin_product, local: true) do |form| %>
  <% if admin_product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_product.errors.count, "error") %> prohibited this admin_product from being saved:</h2>

      <ul>
      <% admin_product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :admin_product_description %>
  </div>

  <div class="field">
    <%= form.label :barcode %>
    <%= form.text_field :barcode, id: :admin_product_barcode %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/products/edit.html.erb
<h1>Editing Admin Product</h1>

<%= render 'form', admin_product: @admin_product %>

<%= link_to 'Show', @admin_product %> |
<%= link_to 'Back', admin_products_path %>

app/views/admin/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Products</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Barcode</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_products.each do |admin_product| %>
      <tr>
        <td><%= admin_product.description %></td>
        <td><%= admin_product.barcode %></td>
        <td><%= link_to 'Show', admin_product %></td>
        <td><%= link_to 'Edit', edit_admin_product_path(admin_product) %></td>
        <td><%= link_to 'Destroy', admin_product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin Product', new_admin_product_path %>

app/views/admin/products/new.html.erb
<h1>New Admin Product</h1>

<%= render 'form', admin_product: @admin_product %>

<%= link_to 'Back', admin_products_path %>

app/views/admin/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @admin_product.description %>
</p>

<p>
  <strong>Barcode:</strong>
  <%= @admin_product.barcode %>
</p>

<%= link_to 'Edit', edit_admin_product_path(@admin_product) %> |
<%= link_to 'Back', admin_products_path %>