config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  get 'static_pages/help'
  get 'password_resets/new'
  get 'password_resets/edit'

  root 'static_pages#home'

  namespace :admin do
    resources :products
    resources :users
    get :dashboard, to: 'dashboard#index'
  end

  get    :login,   to: 'sessions#new'
  post   :login,   to: 'sessions#create'
  delete :logout,  to: 'sessions#destroy'
  get :signup,  to: 'admin/users#new'

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:create, :edit, :update]
end

app/views/layouts/_footer.erb
<footer class="mastfoot mt-auto">
  <div class="inner">
    <p>Cover template for </p>
  </div>
</footer>

app/views/layouts/_header_menu.erb
<header class="masthead mb-auto">
  <div class="inner">
    <h3 class="masthead-brand">ADDStock</h3>
    <nav class="nav nav-masthead justify-content-center">
      <%= link_to t('static_pages.home'), root_path, class: 'nav-link' %>
      <%= link_to t('static_pages.help'), static_pages_help_path, class: 'nav-link' %>
      <%= link_to t('session.new.btn.login'), login_path, class: 'nav-link' %>
    </nav>
  </div>
</header>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'admin', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/admin/header' %>
    <%= render 'layouts/admin/messages' %>
    <%= render 'layouts/admin/top_menu' %>
    <%= render 'layouts/admin/sidebar' %>
    <div id="content">
      <%= yield %>
    </div>

    <script type="text/javascript">
      // This function is called from the pop-up menus to transfer to
      // a different page. Ignore if the value returned is a null string:
      function goPage (newURL) {

          // if url is empty, skip the menu dividers and reset the menu selection to default
          if (newURL != "") {
          
              // if url is "-", it is this page -- reset the menu:
              if (newURL == "-" ) {
                  resetMenu();            
              } 
              // else, send page to designated URL            
              else {  
                document.location.href = newURL;
              }
          }
      }

    // resets the menu selection upon entry to this page:
    function resetMenu() {
       document.gomenu.selector.selectedIndex = 2;
    }
    </script>
  </body>
</html>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="text-center">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
    <%= render 'layouts/header_menu' %>

  <main role="main" class="inner cover">
    <%= yield %>
  </main>

  <%= render 'layouts/footer' %>
</div>
</body>
</html>

app/views/layouts/clear.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'clear', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'clear', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </body>
</html>